import Footer from '@/components/footer';
import Navbar from '@/components/navbar';
import TransitionProvider from '@/components/transitionProvider';
import '@/styles/globals.css'
import { Inter } from "next/font/google"
import Head from 'next/head';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function App({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>Michael Obi</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${inter.variable} font-inter bg-white w-full min-h-screen`}>
        {/* <TransitionProvider> */}
          <Navbar />
          <Component {...pageProps} />
          <Footer />
        {/* </TransitionProvider> */}
      </main>
    </>
  )
}
